--!nocheck
--!nolint
return {
	["SourceSansPro"] = "rbxasset://fonts/families/SourceSansPro.json",
	["Montserrat"] = "rbxasset://fonts/families/GothamSSm.json",
	["Roboto"] = "rbxasset://fonts/families/Roboto.json",
	["HighwayGothic"] = "rbxasset://fonts/families/HighwayGothic.json",
	["FredokaOne"] = "rbxasset://fonts/families/FredokaOne.json",
	["BuilderSans"] = "rbxassetid://16658221428",
	["Creepster"] = "rbxasset://fonts/families/Creepster.json",
}